name: Deploy AWS Lambda and S3

on:
  push:
    branches:
      - '**'

permissions:
  id-token: write  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::682033475665:role/github.to.aws.oicd
          aws-region: eu-central-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Initialize Terraform
        run: terraform init
        working-directory: Terraform/

      - name: Terraform Format
        run: terraform fmt -check
        working-directory: Terraform/

      - name: Terraform Plan
        run: terraform plan -input=false
        working-directory: Terraform/

      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false
        working-directory: Terraform/
